baseURL = 'https://blog.kvak.net'
languageCode = 'en-us'
title = 'Personal tech & sec blog'
theme = 'm10c'

[params]
  author = "Keijo Korte"
  description = "..||.."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/korteke"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/korteke"
